# Wallpaper
background {
    monitor = DP-2
    path = ~/Pictures/wallpapers/cat-cropped.jpg
}

# Date
label {
    monitor = DP-2
    text = cmd[update:3600000] date +"%A, %B %-d %Y"
    color = rgb(0,0,0) 
    font_size = 24
    font_family = LMRoman10
    position = 0, 375
    halign = center
    valign = center
}

# Time
label {
    monitor = DP-2
    text = cmd[update:1000] date +"%-I:%M"
    color = rgb(0,0,0)
    font_size = 95
    font_family = LMRoman10 
    position = 0, 275
    halign = center
    valign = center
}

